apiVersion: v1
kind: Service
metadata:
  name: simple-crud
  namespace: core
spec:
  selector:
    app: simple-crud
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-crud-config
  namespace: core
data:
  APP_NAME: simple-crud
  APP_PORT: "3000"
  PYROSCOPE_URI: "http://ps-pyroscope-distributor.shared.cluster"
  PYROSCOPE_TENANTID: "edot-shared-grafana"
  OTEL_RPC_URI: al-core-alloy:4317
  EXTERNAL_GRPC: "grpc-server:50051"
  EXTERNAL_HTTP: http://simple-crud.core.svc.cluster.local:3000/products
  MONGO_URI: mongodb://root:mypswd123@0.tcp.ap.ngrok.io:18932
  # MONGO_URI: mongodb+srv://for-boilerplate-testing-only:uf61wEt3tkl6rF2k@svc-user-develop.m1aqy.mongodb.net/?retryWrites=true&w=majority
  # MONGO_URI: mongodb://for-boilerplate-testing-only:uf61wEt3tkl6rF2k@svc-user-develop-shard-00-00.m1aqy.mongodb.net:27017,svc-user-develop-shard-00-01.m1aqy.mongodb.net:27017,svc-user-develop-shard-00-02.m1aqy.mongodb.net:27017/?ssl=true&replicaSet=atlas-duagkl-shard-0&authSource=admin&retryWrites=true&w=majority&ssl=true
  MONGO_DB_NAME: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-crud
  namespace: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-crud
  template:
    metadata:
      labels:
        app: simple-crud
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: simple-crud
          image: ifundeasy/simple-crud:rc1.0.5-3
          imagePullPolicy: Always
          tty: true
          envFrom:
            - configMapRef:
                name: simple-crud-config
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 3000
