replicaCount: 1

controller:
  type: deployment

image:
  repository: grafana/alloy
  tag: latest
  pullPolicy: IfNotPresent

alloy:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraPorts:
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: http-otlp
      port: 4318
      targetPort: 4318
      protocol: TCP

  configMap:
    create: true
    name: alloy-config
    content: |
      livedebugging {
        enabled = true
      }

      logging {
        level  = "info"
        format = "logfmt"
      }

      discovery.kubernetes "pod" {
        role = "pod"

        namespaces {
          names = ["product-two"]
        }
      }

      // ── LOGGING ─────────────────────────────────────────────
      loki.write "default" {
        endpoint {
          url     = "http://lk-loki-gateway.grafana.svc.cluster.local/loki/api/v1/push"
          headers = {
            "X-Scope-OrgID" = "myorg-production-producttwo",
          }
        }
      }

      loki.source.kubernetes "default" {
        targets = discovery.kubernetes.pod.targets
        forward_to = [loki.write.default.receiver]
      }

      // ── TRACING ─────────────────────────────────────────────
      otelcol.receiver.otlp "traces" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }

        http {
          endpoint = "0.0.0.0:4318"
        }

        output {
          traces = [otelcol.processor.attributes.traces.input]
        }
      }

      otelcol.processor.attributes "traces" {
        action {
          key    = "business-unit"
          value  = "product-two"
          action = "insert"
        }

        output {
          traces = [otelcol.processor.batch.traces.input]
        }
      }

      otelcol.processor.batch "traces" {
        output {
          traces = [otelcol.exporter.otlp.traces.input]
        }
      }

      otelcol.exporter.otlp "traces" {
        client {
          endpoint = "tp-tempo-distributor.grafana.svc.cluster.local:4317"
          headers  = {
            "X-Scope-OrgID" = "myorg-production-producttwo",
          }

          tls {
            insecure             = true
            insecure_skip_verify = true
          }
        }
      }
