# -- Use admin user/pass from secret
admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

datasources:
  datasources.yaml:
    apiVersion: 1
    # -- Datasources linked to the Grafana instance. Override if you disable any components.
    datasources:
      # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
      - name: Loki
        uid: loki
        type: loki
        url: http://loki-loki-gateway
        isDefault: false
      # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-data-source
      - name: Mimir
        uid: prom
        type: prometheus
        url: http://mimir-mimir-nginx/prometheus
        isDefault: true
      # https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
      - name: Tempo
        uid: tempo
        type: tempo
        url: http://mimir-tempo-query-frontend:3100
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
          lokiSearch:
            datasourceUid: loki
          tracesToMetrics:
            datasourceUid: prom
          serviceMap:
            datasourceUid: prom