replicaCount: 1

controller:
  type: deployment

alloy:
  configMap:
    create: true
    name: alloy-config
    content: |
      discovery.kubernetes "k8s" {
        role = "pod"

        namespaces {
          names = ["grafana"]
        }
      }

      loki.write "default" {
        endpoint {
          url     = "http://lk-loki-gateway/loki/api/v1/push"
          headers = {
            "X-Scope-OrgID" = "myorg-production-grafana",
          }
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.k8s.targets
        forward_to = [loki.write.default.receiver]
      }

image:
  repository: grafana/alloy
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  ports:
    - name: http-metrics
      port: 12345
      targetPort: 12345

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
