# NOTE: https://medium.com/@martinko.komorny/grafana-agent-alloy-mimir-minio-grafana-in-kubernetes-42cb63020f75
query_scheduler:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

querier:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

queryFrontend:
  query:
    enabled: true
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

ingester:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 400m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 512Mi
  zoneAwareReplication: # zone-aware replication is the replication of data across failure domains, Enable it if you want to use it, https://grafana.com/docs/mimir/latest/configure/configure-zone-aware-replication/
    enabled: false

store_gateway:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi
  zoneAwareReplication: # zone-aware replication is the replication of data across failure domains, Enable it if you want to use it, https://grafana.com/docs/mimir/latest/configure/configure-zone-aware-replication/
    enabled: false

gateway:
  enabled: true
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

disributor:
  enabled: true
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 400m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 512Mi

compactor:
  enabled: true
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

nginx:
  enabled: true
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

alertmanager:
  enabled: true
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

ruler:
  enabled: true
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

overrides_exporter:
  enabled: true
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  resources:
    requests:
      cpu: 160m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 256Mi

mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: host.docker.internal:9000
          access_key_id: default
          secret_access_key: mypswd123
          bucket_name: grafana-mimir-ruler
          region: us-east-1
          insecure: true # minio/localstack = true, AWS S3 = false
          http:
            insecure_skip_verify: true
    alertmanager_storage:
      backend: s3
      s3:
        bucket_name: grafana-mimir-alertmanager
    ruler_storage:
      backend: s3
      s3:
        bucket_name: grafana-mimir-ruler
    blocks_storage:
      backend: s3
      s3:
        bucket_name: grafana-mimir-blocks

    memberlist:
      cluster_label: "mimir"
      cluster_label_verification_disabled: false
    server:
      log_level: debug
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000
    limits:
      max_label_names_per_series: 120
      max_global_series_per_user: 12000000
      ingestion_burst_size: 200000
      ingestion_rate: 150000
      max_global_series_per_metric: 200000000
      compactor_blocks_retention_period: 24h
    compactor:
      compaction_interval: 24h
## disabled services ##
minio:
  enabled: false
