# -- Use admin user/pass from secret
admin:
  existingSecret: gf-admin-secret
  userKey: admin-user
  passwordKey: admin-password

datasources:
  datasources.yaml:
    apiVersion: 1
    # -- Datasources linked to the Grafana instance. Override if you disable any components.
    datasources:
    
      # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
      - name: loki-product-one
        uid: loki-product-one
        type: loki
        url: http://lk-loki-gateway.grafana.svc.cluster.local
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "product-one"

      # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
      - name: loki-product-two
        uid: loki-product-two
        type: loki
        url: http://lk-loki-gateway.grafana.svc.cluster.local
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "product-two"

      # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-data-source
      - name: mimir-product-one
        uid: mimir-product-one
        type: prometheus
        url: http://mr-mimir-distributed-nginx/prometheus
        isDefault: false
        access: proxy
        editable: true
        
      # https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
      - name: tempo-product-one
        uid: tempo-product-one
        type: tempo
        url: http://tp-tempo.grafana.svc.cluster.local
        isDefault: false
        access: proxy
        editable: true
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
          lokiSearch:
            datasourceUid: loki
          tracesToMetrics:
            datasourceUid: prom
          serviceMap:
            datasourceUid: prom