# -- Use admin user/pass from secret
admin:
  existingSecret: gf-admin-secret
  userKey: admin-user
  passwordKey: admin-password

replicas: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 400Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    # -- Datasources linked to the Grafana instance. Override if you disable any components.
    datasources:
      # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
      - name: loki-myorg-production-grafana
        uid: loki-myorg-production-grafana
        type: loki
        url: http://lk-loki-gateway
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-grafana"

      - name: loki-myorg-production-productone
        uid: loki-myorg-production-productone
        type: loki
        url: http://lk-loki-gateway
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          derivedFields:
            - datasourceUid: tempo-myorg-production-productone
              name: traceId
              matcherRegex: '"trace_id"\s*:\s*"([a-fA-F0-9]+)"'
              url: "$${__value.raw}"
        secureJsonData:
          httpHeaderValue1: "myorg-production-productone"

      - name: loki-myorg-production-producttwo
        uid: loki-myorg-production-producttwo
        type: loki
        url: http://lk-loki-gateway
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          derivedFields:
            - datasourceUid: tempo-myorg-production-producttwo
              name: traceId
              matcherRegex: '"trace_id"\s*:\s*"([a-fA-F0-9]+)"'
              url: "$${__value.raw}"
        secureJsonData:
          httpHeaderValue1: "myorg-production-producttwo"

      # https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
      - name: tempo-myorg-production-grafana
        uid: tempo-myorg-production-grafana
        type: tempo
        url: http://tp-tempo-gateway
        isDefault: false
        access: proxy
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          tracesToLogsV2:
            datasourceUid: loki-myorg-production-grafana
          lokiSearch:
            datasourceUid: loki-myorg-production-grafana
          tracesToMetrics:
            datasourceUid: mimir-myorg-production-grafana
          serviceMap:
            datasourceUid: pyroscope-myorg-production-grafana
          traceToProfiles:
            datasourceUid: pyroscope-myorg-production-grafana
        secureJsonData:
          httpHeaderValue1: "myorg-production-grafana"

      - name: tempo-myorg-production-productone
        uid: tempo-myorg-production-productone
        type: tempo
        url: http://tp-tempo-gateway
        isDefault: false
        access: proxy
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          tracesToLogsV2:
            datasourceUid: loki-myorg-production-productone
          lokiSearch:
            datasourceUid: loki-myorg-production-productone
          tracesToMetrics:
            datasourceUid: mimir-myorg-production-productone
          serviceMap:
            datasourceUid: pyroscope-myorg-production-productone
          traceToProfiles:
            datasourceUid: pyroscope-myorg-production-productone
        secureJsonData:
          httpHeaderValue1: "myorg-production-productone"

      - name: tempo-myorg-production-producttwo
        uid: tempo-myorg-production-producttwo
        type: tempo
        url: http://tp-tempo-gateway
        isDefault: false
        access: proxy
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          tracesToLogsV2:
            datasourceUid: loki-myorg-production-producttwo
          lokiSearch:
            datasourceUid: loki-myorg-production-producttwo
          tracesToMetrics:
            datasourceUid: mimir-myorg-production-producttwo
          serviceMap:
            datasourceUid: pyroscope-myorg-production-producttwo
          traceToProfiles:
            datasourceUid: pyroscope-myorg-production-producttwo
        secureJsonData:
          httpHeaderValue1: "myorg-production-producttwo"

      - name: mimir-myorg-production-grafana
        uid: mimir-myorg-production-grafana
        type: prometheus
        url: http://mr-mimir-query-frontend:8080/prometheus
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-grafana"

      - name: mimir-myorg-production-productone
        uid: mimir-myorg-production-productone
        type: prometheus
        url: http://mr-mimir-query-frontend:8080/prometheus
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-productone"

      - name: mimir-myorg-production-producttwo
        uid: mimir-myorg-production-producttwo
        type: prometheus
        url: http://mr-mimir-query-frontend:8080/prometheus
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-producttwo"

      - name: pyroscope-myorg-production-grafana
        uid: pyroscope-myorg-production-grafana
        type: phlare
        access: proxy
        url: http://ps-pyroscope-query-frontend:4040
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-grafana"

      - name: pyroscope-myorg-production-productone
        uid: pyroscope-myorg-production-productone
        type: phlare
        access: proxy
        url: http://ps-pyroscope-query-frontend:4040
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-productone"

      - name: pyroscope-myorg-production-producttwo
        uid: pyroscope-myorg-production-producttwo
        type: phlare
        access: proxy
        url: http://ps-pyroscope-query-frontend:4040
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-producttwo"
