# -- Use admin user/pass from secret
admin:
  existingSecret: gf-admin-secret
  userKey: admin-user
  passwordKey: admin-password

replicas: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2

datasources:
  datasources.yaml:
    apiVersion: 1
    # -- Datasources linked to the Grafana instance. Override if you disable any components.
    datasources:
      # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
      - name: loki-myorg-production-grafana
        uid: loki-myorg-production-grafana
        type: loki
        url: http://lk-loki-gateway
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-grafana"

      - name: loki-myorg-production-productone
        uid: loki-myorg-production-productone
        type: loki
        url: http://lk-loki-gateway
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-productone"

      - name: loki-myorg-production-producttwo
        uid: loki-myorg-production-producttwo
        type: loki
        url: http://lk-loki-gateway
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "myorg-production-producttwo"

      # https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
      - name: tempo-myorg-production-grafana
        uid: tempo-myorg-production-grafana
        type: tempo
        url: http://tp-tempo-gateway
        isDefault: false
        access: proxy
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          tracesToLogsV2:
            datasourceUid: loki-myorg-production-grafana
          lokiSearch:
            datasourceUid: loki-myorg-production-grafana
          tracesToMetrics:
            datasourceUid: mimir-myorg-production-grafana
          serviceMap:
            datasourceUid: pyroscope-myorg-production-grafana
        secureJsonData:
          httpHeaderValue1: "myorg-production-grafana"

      - name: tempo-myorg-production-productone
        uid: tempo-myorg-production-productone
        type: tempo
        url: http://tp-tempo-gateway
        isDefault: false
        access: proxy
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          tracesToLogsV2:
            datasourceUid: loki-myorg-production-productone
          lokiSearch:
            datasourceUid: loki-myorg-production-productone
          tracesToMetrics:
            datasourceUid: mimir-myorg-production-productone
          serviceMap:
            datasourceUid: pyroscope-myorg-production-productone
        secureJsonData:
          httpHeaderValue1: "myorg-production-productone"

      - name: tempo-myorg-production-producttwo
        uid: tempo-myorg-production-producttwo
        type: tempo
        url: http://tp-tempo-gateway
        isDefault: false
        access: proxy
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          tracesToLogsV2:
            datasourceUid: loki-myorg-production-producttwo
          lokiSearch:
            datasourceUid: loki-myorg-production-producttwo
          tracesToMetrics:
            datasourceUid: mimir-myorg-production-producttwo
          serviceMap:
            datasourceUid: pyroscope-myorg-production-producttwo
        secureJsonData:
          httpHeaderValue1: "myorg-production-producttwo"

      # # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-data-source
      # - name: mimir
      #   uid: mimir
      #   type: prometheus
      #   url: http://mr-mimir-distributed-gateway/prometheus
      #   isDefault: false
      #   access: proxy
      #   editable: true
